package com.grindaga.crissaegrim.controllers

import com.grindaga.crissaegrim.maps.RelicsMap
import com.grindaga.crissaegrim.model.RelicsScope
import com.grindaga.crissaegrim.objects.Slot
import tornadofx.*

class RelicsController: Controller() {
    val relicsScope = RelicsScope()
    val relicsMap = RelicsMap()
    val relics = relicsScope.relics

    init {
        relics.soulOfBat.setValue(0)
        relics.fireOfBat.setValue(0)
        relics.echoOfBat.setValue(0)
        relics.forceOfEcho.setValue(0)
        relics.soulOfWolf.setValue(0)
        relics.powerOfWolf.setValue(0)
        relics.skillOfWolf.setValue(0)
        relics.formOfMist.setValue(0)
        relics.powerOfMist.setValue(0)
        relics.gasCloud.setValue(0)
        relics.cubeOfZoe.setValue(0)
        relics.spiritOrb.setValue(0)
        relics.gravityBoots.setValue(0)
        relics.leapStone.setValue(0)
        relics.holySymbol.setValue(0)
        relics.faerieScroll.setValue(0)
        relics.jewelOfOpen.setValue(0)
        relics.mermanStatue.setValue(0)
        relics.batCard.setValue(0)
        relics.ghostCard.setValue(0)
        relics.faerieCard.setValue(0)
        relics.demonCard.setValue(0)
        relics.swordCard.setValue(0)
        relics.heartOfVlad.setValue(0)
        relics.toothOfVlad.setValue(0)
        relics.ribOfVlad.setValue(0)
        relics.ringOfVlad.setValue(0)
        relics.eyeOfVlad.setValue(0)
    }

    fun loadFromSlot(slot: Slot) {
        relics.soulOfBat.setValue(slot.read(relicsMap.soulOfBat))
        relics.fireOfBat.setValue(slot.read(relicsMap.fireOfBat))
        relics.echoOfBat.setValue(slot.read(relicsMap.echoOfBat))
        relics.forceOfEcho.setValue(slot.read(relicsMap.forceOfEcho))
        relics.soulOfWolf.setValue(slot.read(relicsMap.soulOfWolf))
        relics.powerOfWolf.setValue(slot.read(relicsMap.powerOfWolf))
        relics.skillOfWolf.setValue(slot.read(relicsMap.skillOfWolf))
        relics.formOfMist.setValue(slot.read(relicsMap.formOfMist))
        relics.powerOfMist.setValue(slot.read(relicsMap.powerOfMist))
        relics.gasCloud.setValue(slot.read(relicsMap.gasCloud))
        relics.cubeOfZoe.setValue(slot.read(relicsMap.cubeOfZoe))
        relics.spiritOrb.setValue(slot.read(relicsMap.spiritOrb))
        relics.gravityBoots.setValue(slot.read(relicsMap.gravityBoots))
        relics.leapStone.setValue(slot.read(relicsMap.leapStone))
        relics.holySymbol.setValue(slot.read(relicsMap.holySymbol))
        relics.faerieScroll.setValue(slot.read(relicsMap.faerieScroll))
        relics.jewelOfOpen.setValue(slot.read(relicsMap.jewelOfOpen))
        relics.mermanStatue.setValue(slot.read(relicsMap.mermanStatue))
        relics.batCard.setValue(slot.read(relicsMap.batCard))
        relics.ghostCard.setValue(slot.read(relicsMap.ghostCard))
        relics.faerieCard.setValue(slot.read(relicsMap.faerieCard))
        relics.demonCard.setValue(slot.read(relicsMap.demonCard))
        relics.swordCard.setValue(slot.read(relicsMap.swordCard))
        relics.heartOfVlad.setValue(slot.read(relicsMap.heartOfVlad))
        relics.toothOfVlad.setValue(slot.read(relicsMap.toothOfVlad))
        relics.ribOfVlad.setValue(slot.read(relicsMap.ribOfVlad))
        relics.ringOfVlad.setValue(slot.read(relicsMap.ringOfVlad))
        relics.eyeOfVlad.setValue(slot.read(relicsMap.eyeOfVlad))
    }

    fun writeToSlot(slot: Slot) {
        slot.write(relicsMap.soulOfBat, relics.soulOfBat.value.toInt())
        slot.write(relicsMap.fireOfBat, relics.fireOfBat.value.toInt())
        slot.write(relicsMap.echoOfBat, relics.echoOfBat.value.toInt())
        slot.write(relicsMap.forceOfEcho, relics.forceOfEcho.value.toInt())
        slot.write(relicsMap.soulOfWolf, relics.soulOfWolf.value.toInt())
        slot.write(relicsMap.powerOfWolf, relics.powerOfWolf.value.toInt())
        slot.write(relicsMap.skillOfWolf, relics.skillOfWolf.value.toInt())
        slot.write(relicsMap.formOfMist, relics.formOfMist.value.toInt())
        slot.write(relicsMap.powerOfMist, relics.powerOfMist.value.toInt())
        slot.write(relicsMap.gasCloud, relics.gasCloud.value.toInt())
        slot.write(relicsMap.cubeOfZoe, relics.cubeOfZoe.value.toInt())
        slot.write(relicsMap.spiritOrb, relics.spiritOrb.value.toInt())
        slot.write(relicsMap.gravityBoots, relics.gravityBoots.value.toInt())
        slot.write(relicsMap.leapStone, relics.leapStone.value.toInt())
        slot.write(relicsMap.holySymbol, relics.holySymbol.value.toInt())
        slot.write(relicsMap.faerieScroll, relics.faerieScroll.value.toInt())
        slot.write(relicsMap.jewelOfOpen, relics.jewelOfOpen.value.toInt())
        slot.write(relicsMap.mermanStatue, relics.mermanStatue.value.toInt())
        slot.write(relicsMap.batCard, relics.batCard.value.toInt())
        slot.write(relicsMap.ghostCard, relics.ghostCard.value.toInt())
        slot.write(relicsMap.faerieCard, relics.faerieCard.value.toInt())
        slot.write(relicsMap.demonCard, relics.demonCard.value.toInt())
        slot.write(relicsMap.swordCard, relics.swordCard.value.toInt())
        slot.write(relicsMap.heartOfVlad, relics.heartOfVlad.value.toInt())
        slot.write(relicsMap.toothOfVlad, relics.toothOfVlad.value.toInt())
        slot.write(relicsMap.ribOfVlad, relics.ribOfVlad.value.toInt())
        slot.write(relicsMap.ringOfVlad, relics.ringOfVlad.value.toInt())
        slot.write(relicsMap.eyeOfVlad, relics.eyeOfVlad.value.toInt())
    }
}